### ISSUE TITLE
`arbitrary_self_types` support

### ISSUE THREAD

**Issue by adetaylor** [DerickEddington/cfg_rust_features#1]
Hi, I would use this crate if it probed for `arbitrary_self_types`. Raising an issue as requested by your helpful error messages. Thanks!

**Comment by DerickEddington** [comment]
Thanks for your interest!  I'll look into implementing support for this and will publish a new version with that if I succeed.  It'll probably be around the end of this month until I can find enough free time.  (If you already implemented it, feel free to open a pull request, but no pressure, I'm glad to do it.)

**Comment by DerickEddington** [comment]
I've implemented support for the `arbitrary_self_types` feature, as well as improved the package in some other ways, and have tested all this, and this is pushed.

But I haven't yet published a new version to crates.io, since I still need to do final review and testing (I'm planning on trying some basic use from your `autocxx`).  I should be able to publish it soon (maybe by tomorrow night).

If you'd like, you may currently use the crate from my repo as version `0.1.1-pre`.

**Comment by DerickEddington** [comment]
@adetaylor, I've [published new version `0.1.1` to crates.io](https://crates.io/crates/cfg_rust_features) that supports the feature and provides the new `rust_lang_feature = "arbitrary_self_types"` `cfg` option.

Also, I made [a demonstration of how it could be used by `autocxx`](https://github.com/google/autocxx/compare/main...DerickEddington:autocxx:derick/cfg_rust_features/demo), that uses it where I found that seemed relevant to `arbitrary_self_types`, and that shows some various ways of how it can enable code to automatically adjust to whether Rust features are stable or unstable.  (Of course, all this might not be how you end-up wanting to use it.)

The [README](https://github.com/DerickEddington/cfg_rust_features/blob/main/README.md) is also now a little improved to better describe its capabilities.
